<?php
    $language["GW-MANUFACTURER"] = "Manufacturer";
    $language["ADD-GW-NAV"] = "Add Gateway";
    $language["SEARCH-GW-NAV"] = "Search";
    $language["STATS-NAV"] = "Stats";
    $language["GW-INFORMATION"] = "Gateway Information";
    $language["GR-ST-TITLE"] ="Packets per second on the entire network";
    $language["GR-ST-SIDETITLE"] = "Packets";
    $language["GR-ST-PACKETSPERSECOND"] = "Packets per second";
    $language["GW-NAME"] = "Name";
    $language["GW-LATITUDE"] = "Latitude";
    $language["GW-LONGITUDE"] = "Longitude";
    $language["GR-GW-UPLPACKETSPERSECOND"] = "Uplink packets per second";
    $language["GR-GW-UPLPACKETSWHITVALIDCRCPERSECOND"] = "Uplink packets with valid CRC per second";
    $language["GR-GW-FORWARDEDPACKETSPERSECOND"] = "Forwarded packets per second";
    $language["GR-GW-DOWNLINKPACKETSPERSECOND"] = "Downlink packets per second";
    $language["GR-GW-EMITTEDPACKETSPERSECOND"] = "Emitted packets per second";
    $language["GR-GW-TITLE"] = "Complete stats of the gateway";
    $language["PR-PROFILE"] = "Profile";
    $language["PR-SURNAME"] = "Surname";
    $language["PR-EMAIL"] = "Email address";
    $language["ED-BUTTON"] = "Edit";
    $language["EDIT-SUCCESS"] = "Change made succesfully!";
    $language["OLD-PASS"] = "Insert old password";
    $language["CHANGE-PASSWORD"] = "Change password";
    $language["INS-PASSWORD"] = "Insert new password";
    $language["REINS-PASSWORD"] = "Insert again new password";
    $language["ADD-IMMAGE"] = "Modify profile immage";
?>